# Generated by Django 2.2.5 on 2020-03-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
