# Generated by Django 3.0.5 on 2020-04-03 13:26

from django.db import migrations, models
import musers.models


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0002_muser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='profile_photo',
            field=models.FileField(upload_to=musers.models.upload_to_image),
        ),
    ]
