# Generated by Django 3.0.3 on 2020-04-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0003_auto_20200403_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
