# Generated by Django 3.0.3 on 2020-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0004_auto_20200408_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
