# Generated by Django 3.0.5 on 2020-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0006_auto_20200412_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='muser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
