# Generated by Django 3.0.3 on 2020-05-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0011_auto_20200415_0131'),
        ('musers', '0007_auto_20200412_1817'),
    ]

    operations = [
    ]
