# Generated by Django 3.0.3 on 2020-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musers', '0012_merge_20200510_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
