# Generated by Django 2.2.4 on 2019-10-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='issueKey',
        ),
    ]
