# Generated by Django 2.2.4 on 2019-10-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDetail', '0002_auto_20191023_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issueKey',
            new_name='issueTitle',
        ),
    ]
