# Generated by Django 2.2.4 on 2019-10-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDetail', '0003_auto_20191025_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProductDetail.Product'),
        ),
    ]
