# Generated by Django 2.2.4 on 2019-10-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDetail', '0004_auto_20191025_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueTitle',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
